### ISSUE TITLE
tap-github --about is broken

### ISSUE THREAD

**Issue by ericboucher** [MeltanoLabs/tap-github#106]
`tap-github --about` requires a valid config file, which kinda defeats the purpose:

```
ericboucher@Erics-MBP website % tap-github --about
time=2022-04-12 15:36:20 name=tap-github level=INFO message=Skipping parse of env var settings...
time=2022-04-12 15:36:20 name=tap-github level=INFO message=Config validation passed with 0 errors and 0 warnings.
time=2022-04-12 15:36:20 name=root level=INFO message=Operator '__else__=None' was not found. Unmapped streams will be included in output.
Traceback (most recent call last):
  File "/opt/homebrew/bin/tap-github", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 467, in cli
    tap = cls(  # type: ignore  # Ignore 'type not callable'
  File "/opt/homebrew/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 92, in __init__
    self.input_catalog or self._singer_catalog
  File "/opt/homebrew/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 235, in _singer_catalog
    for stream in self.streams.values()
  File "/opt/homebrew/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 118, in streams
    for stream in self.load_streams():
  File "/opt/homebrew/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 267, in load_streams
    for stream in self.discover_streams():
  File "/opt/homebrew/lib/python3.9/site-packages/tap_github/tap.py", line 65, in discover_streams
    raise ValueError(
ValueError: This tap requires one and only one of the following path options: {'organizations', 'user_ids', 'user_usernames', 'repositories', 'searches'}.
```

Let's make sure anyone can run this command after installing tap-github.

**Comment by ericboucher** [comment]
@Ry-DS could you have a quick look? I think the PR adding the missing singer streams broke this :)
