### ISSUE TITLE
Add HTTP Status 204 to `tolerated_http_errors` for contributors streams

### ISSUE THREAD

**Issue by epapineau** [MeltanoLabs/tap-github#140]
`/repos/{org}/{repo}/contributors` and `/repos/{org}/{repo}/stats/contributors` both return HTTP Status 204 when called for [an empty repository](https://github.com/epapineau/example-empty-repo). Example Postman request:

![Screen Shot 2022-05-28 at 11 14 41 PM](https://user-images.githubusercontent.com/20958052/170854888-add0419f-3b87-4fa8-9aab-291ae237216a.png)

As a result the Contributors, Anonymous Contributors, and Stats Contributors streams each return `JSONDecodeError` when attempting to parse an empty response:

```python
time=2022-05-28 23:34:30 name=tap-github level=INFO message=INFO METRIC: {'type': 'timer', 'metric': 'http_request_duration', 'value': 0.435061, 'tags': {'endpoint': '/search/repositories', 'http_status_code': 200, 'status': 'succeeded', 'context': {'search_name': 'empty-repo', 'search_query': 'user:epapineau example-empty-repo'}}}
time=2022-05-28 23:34:30 name=tap-github level=INFO message=Beginning full_table sync of 'contributors' with context: {'org': 'epapineau', 'repo': 'example-empty-repo', 'repo_id': 497421330}...
time=2022-05-28 23:34:30 name=tap-github level=INFO message=Tap has custom mapper. Using 1 provided map(s).
time=2022-05-28 23:34:30 name=tap-github level=INFO message=Found 1 'GITHUB_TOKEN' environment variables for authentication.
time=2022-05-28 23:34:30 name=tap-github level=INFO message=Tap will run with 1 auth tokens
time=2022-05-28 23:34:31 name=tap-github level=INFO message=INFO METRIC: {'type': 'timer', 'metric': 'http_request_duration', 'value': 0.313254, 'tags': {'endpoint': '/repos/{org}/{repo}/contributors', 'http_status_code': 204, 'status': 'succeeded', 'context': {'org': 'epapineau', 'repo': 'example-empty-repo', 'repo_id': 497421330}}}
Traceback (most recent call last):
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/bin/tap-github", line 8, in <module>
    sys.exit(cli())
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 499, in cli
    tap.sync_all()
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 379, in sync_all
    stream.sync()
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 1020, in sync
    self._sync_records(context)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 962, in _sync_records
    self._sync_children(child_context)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 1025, in _sync_children
    child_stream.sync(context=child_context)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 1020, in sync
    self._sync_records(context)
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 946, in _sync_records
    for record_result in self.get_records(current_context):
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/streams/rest.py", line 424, in get_records
    for record in self.request_records(context):
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/singer_sdk/streams/rest.py", line 323, in request_records
    yield from self.parse_response(resp)
  File "/Users/elizepapineau/dev/tap-github/tap_github/client.py", line 226, in parse_response
    resp_json = response.json()
  File "/Users/elizepapineau/dev/tap-github/venv/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```

**Comment by laurentS** [comment]
Thanks for reporting this. I'm closing this now as I just merged your PR.
