### ISSUE TITLE
ValueError: not enough values to unpack (expected at least 1, got 0) in repository_streams

### ISSUE THREAD

**Issue by sicarul** [MeltanoLabs/tap-github#191]
Hey folks! I'm having this issue with the tap, is there any way to mitigate it?

Thanks!

```
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.397630Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.397844Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/bin/tap-github", line 8, in <module> cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.398049Z [info     ]     sys.exit(cli())            cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.398256Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__ cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.398499Z [info     ]     return self.main(*args, **kwargs) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.398708Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.398963Z [info     ]     rv = self.invoke(ctx)      cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.399173Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.399375Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.399585Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.399788Z [info     ]     return __callback(*args, **kwargs) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.400013Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 509, in cli cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.400216Z [info     ]     tap.sync_all()             cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.400427Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 381, in sync_all cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.400631Z [info     ]     stream.sync()              cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.400828Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/core.py", line 1113, in sync cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.401065Z [info     ]     for _ in self._sync_records(context=context): cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.401320Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/core.py", line 1020, in _sync_records cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.401553Z [info     ]     self._process_record(      cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.401822Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/core.py", line 968, in _process_record cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.402111Z [info     ]     self._sync_children(child_context) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.402348Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/core.py", line 1119, in _sync_children cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.402579Z [info     ]     child_stream.sync(context=child_context) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.402813Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/core.py", line 1113, in sync cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.403046Z [info     ]     for _ in self._sync_records(context=context): cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.403277Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/core.py", line 1013, in _sync_records cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.403505Z [info     ]     for record_result in self.get_records(current_context): cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.403736Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/rest.py", line 538, in get_records cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.403981Z [info     ]     for record in self.request_records(context): cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.404216Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/streams/rest.py", line 363, in request_records cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.404451Z [info     ]     paginator.advance(resp)    cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.404686Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/pagination.py", line 111, in advance cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.404919Z [info     ]     new_value = self.get_next(response) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.405177Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/singer_sdk/pagination.py", line 453, in get_next cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.405402Z [info     ]     return self.stream.get_next_page_token(response, self.current_value) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.405634Z [info     ]   File "/project/.meltano/extractors/tap-github/venv/lib/python3.10/site-packages/tap_github/repository_streams.py", line 1607, in get_next_page_token cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.405874Z [info     ]     *_, last = results         cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
[2023-04-18, 12:05:44 UTC] {ecs.py:196} INFO - [2023-04-18, 12:05:38 UTC] 2023-04-18T12:05:38.406150Z [info     ] ValueError: not enough values to unpack (expected at least 1, got 0) cmd_type=elb consumer=False name=tap-github producer=True stdio=stderr string_id=tap-github
```

**Comment by edgarrmondragon** [comment]
Closed by #192
